Use the twisted.trial main module instead of the trial script
Trying to fix the deprecations CircleCI job which fails because:

```
ValueError: Unknown endpoint type: 'adopt-socket'
```

Maybe this has something to do with how PYTHONPATH is being set up, I don't
know.